'use strict';function randomHash(a,d){diff=d-a;return a+randomDec()*diff}function randomDec(){return random()}function randomHashArray(a){return a[Math.floor(randomDec()*a.length)]}function radomProbArray(a){let d=randomDec(),b=0;for(let c=0;c<a.length;c++)if(b+=a[c][0],b>d)return a[c][1];return null}function randomHashCoef(a,d,b=1){return Math.floor(randomDec()*(d-a+1)+a)*b}function randomBoolean(){return.5>randomDec()?!0:!1}
function setup(){angleMode(RADIANS);setup_canvas();console.log(dedacode_hashkey);console.log(seed);randomSeed(seed);noiseSeed(seed);randomSetup()}
function draw(){draw_setup_canvas();preloadActive&&time_preload<=preloadMaxTime&&(clear(),preload_canvas(canvas_effettivo),draw_barra_caricamento(this,w/2-w/4,h/2,w/2,h/10,10,colorWhite,canvas_background,time_preload,preloadMaxTime));time_preload==preloadMaxTime+1&&preloadActive&&(clear(),background(canvas_background));if(time_preload>preloadMaxTime&&time_draw<time_draw_end||!preloadActive)draw_scene(canvas_effettivo),image(canvas_effettivo,0,0);time_draw>=time_draw_end&&noLoop()}
function setup_canvas(){if(canvas_dinamico){canvas_visualizzato=createCanvas(windowWidth,windowHeight);proporzione_effettivo=w/h;proporzione_visualizzato=windowWidth/windowHeight;let a=!0;1>proporzione_effettivo&&(a=!1);proporzione_effettivo<proporzione_visualizzato&&1<=proporzione_effettivo&&(a=!1);proporzione_effettivo>=proporzione_visualizzato&&1>proporzione_effettivo&&(a=!0);a?(scale_val=windowWidth/w,diff_x=0,diff_y=(windowHeight-h*scale_val)/2):(scale_val=windowHeight/h,diff_x=(windowWidth-
w*scale_val)/2,diff_y=0);canvas_effettivo=createGraphics(w,h);background(canvas_background)}else canvas_visualizzato=createCanvas(w,h),canvas_effettivo=createGraphics(w,h)}function draw_setup_canvas(){canvas_dinamico&&(translate(diff_x,diff_y),scale(scale_val))}function keyPressed(){"s"==key&&saveCanvas(canvas_effettivo,"_deadcode_"+name_file+".png")}function preload_canvas(a){drawMainTest_001(a,time_preload);time_preload++}function draw_scene(a){time_draw++}
function draw_barra_caricamento(a,d,b,c,e,g,f,k,l,n){a.background(k);a.noFill();a.stroke(f);a.strokeWeight(g);a.rect(d,b,c,e,20);a.fill(f);a.stroke(k);rap_x=(c-2*g)/c;c=l/n*c*rap_x;d_y=(e-.9*e)/2;a.rect(d+g,b+d_y,c,.9*e,20)}
function drawTexture(a,d,b,c){if(1==d){null!=b?(factor=b[0],colorBack=b[1],colorLineLight=b[2],factorLineLight=b[3],colorLineHard=b[4],factorLineHard=b[5],colorDirt=b[6],factorDirt=b[7]):(factor=18,colorBack="#8B8682",colorLineLight="#E1C699",factorLineLight=8,colorLineHard=[220,220,220],factorLineHard=5,colorDirt=[70,70,70,200],factorDirt=35);c.noStroke();c.fill(colorBack);c.beginShape();for(var e=0;e<a.length;e++)c.vertex(a[e].x,a[e].y);c.endShape(CLOSE);var g=w;max_x=0;e=h;max_y=0;for(var f=0;f<
a.length;f++)a[f].x<g&&(g=a[f].x),a[f].x>max_x&&(max_x=a[f].x),a[f].y<e&&(e=a[f].y),a[f].y>max_y&&(max_y=a[f].y);c.noStroke();fDelta=randomHash(60,120);f1=.05;f2=.1;for(f=g;f<max_x;f+=factor/2)for(var k=e;k<max_y;k+=factor/2)c.fill([red(colorDirt),green(colorDirt),blue(colorDirt),noise(f*f1,k*f2)*fDelta]),pointInside(f,k,a)&&c.circle(f+randomHash(-4,4),k+randomHash(-4,4),noise(.002*f,.002*k)*factorDirt);c.strokeWeight(1);c.stroke(colorLineLight);f1=randomHash(1E-4,.005);f2=.4;for(g/=factor;g<max_x/
factor;g++)for(f=e/factor;f<max_y/factor;f++){k=g*factor+sin(noise_value(g,f,f1,f2,TWO_PI))*factor*factorLineLight;let l=f*factor-cos(noise_value(g,f,f1,f2,TWO_PI))*factor*factorLineLight;pointInside(g*factor,f*factor,a)&&c.line(g*factor,f*factor,k,l)}}if(11==d){null!=b?(factor=b[0],colorBack=b[1],colorLineLight=b[2],factorLineLight=b[3],colorLineHard=b[4],factorLineHard=b[5],colorDirt=b[6],factorDirt=b[7]):(factor=18,colorBack="#8B8682",colorLineLight="#E1C699",factorLineLight=8,colorLineHard=[220,
220,220],factorLineHard=5,colorDirt=[70,70,70,200],factorDirt=35);c.noStroke();c.fill(colorBack);b=w;max_x=0;d=h;max_y=0;for(e=0;e<a.length;e++)a[e].x<b&&(b=a[e].x),a[e].x>max_x&&(max_x=a[e].x),a[e].y<d&&(d=a[e].y),a[e].y>max_y&&(max_y=a[e].y);c.noStroke();fDelta=randomHash(60,120);f1=.05;for(f2=.1;b<max_x;b+=factor/2)for(e=d;e<max_y;e+=factor/2)c.fill([red(colorDirt),green(colorDirt),blue(colorDirt),noise(b*f1,e*f2)*fDelta]),pointInside(b,e,a)&&c.circle(b+randomHash(-4,4),e+randomHash(-4,4),noise(.002*
b,.002*e)*factorDirt)}}function noise_value(a,d,b,c,e){return map(noise(a*b,d*c),0,1,0,e)}
function drawCompleteMandala(a,d,b,c,e,g){randomSeed(g);noiseSeed(g);g=int(randomHash(6,9));let f=randomHash(.04,.055);for(let l=0;l<g;l++){var k=c[1];let n=randomHashArray([c[2],c[3]]);0<l&&(k=randomHashArray([c[1],c[2],c[3]]));k=0<l?drawMandalaFoglie(a,d,b*(.46-l*f),0,c[0],k,e-.6*e*l/g):drawMandalaFoglie(a,d,b*(.46-l*f),0,c[0],k,1.1*e);3>randomHash(0,10)&&drawAllManyCircle(a,d,k,b*(.36-l*f),e-.6*e*l/g,c[0],n)}a.stroke(c[0]);a.fill(c[2]);a.circle(d.x,d.y,.25*b);drawMandalaCenter(a,d,.15*b,0,c[0],
255,e)}function drawAllManyCircle(a,d,b,c,e,g,f){a.fill(f);a.strokeWeight(.4*e);a.stroke(g);f=c;5>randomHash(0,10)&&(f=randomHash(.8*c,1.1*c));let k=int(randomHash(2,6)),l=randomHash(c/b,2.8*c/b);e=randomHash(1.5*e,3*e);drawManyCircle(a,d,b,f,l,e,k,0);5>randomHash(0,10)&&(drawManyCircle(a,d,b,c,.07*c,e,1,0),a.fill(g),drawManyCircle(a,d,b,c,.04*c,e,1,0))}
function drawFogliaBez(a,d,b,c,e,g,f,k,l,n,m,q,r,u,p){a.strokeWeight(p);p=TWO_PI/b;g*=p;f*=e;k*=e;l*=e;r*=e;u*=p;for(let t=0;t<b;t++){var v=d.x+sin(t*p)*c,x=d.y+cos(t*p)*c;let A=d.x+sin(t*p)*(c-k),B=d.y+cos(t*p)*(c-k);var y=d.x+sin(t*p)*(c-e),z=d.y+cos(t*p)*(c-e);let C=d.x+sin(t*p)*(c-e+k),D=d.y+cos(t*p)*(c-e+k),E=d.x+sin(t*p-g)*(c-f),F=d.y+cos(t*p-g)*(c-f),G=d.x+sin(t*p+g)*(c-f),H=d.y+cos(t*p+g)*(c-f);n&&a.circle(v,x,l);m&&a.circle(y,z,l);v=E;x=F;y=G;z=H;q&&(v=d.x+sin(t*p-u)*(c-r),x=d.y+cos(t*p-
u)*(c-r),y=d.x+sin(t*p+u)*(c-r),z=d.y+cos(t*p+u)*(c-r));a.bezier(A,B,E,F,v,x,C,D);a.bezier(A,B,G,H,y,z,C,D)}}
function drawMandalaFoglie(a,d,b,c,e,g,f){randomHash(.6*b,.8*b);a.stroke(0);a.noFill();a.strokeWeight(f);c=int(randomHash(2,7));let k=b/20,l=int(randomHash(8,17)),n=randomHash(.4,.7),m=randomHash(.4,.7),q=randomHash(.02,.1),r=randomHash(0,.2),u=!1;4>randomHash(0,10)&&(r=randomHash(.7,.9));5>randomHash(0,10)&&(u=!0);for(let p=c;0<p;p--){let v=b-k*(c-p),x=10*k-k*(c-p);u&&(v=b-k*p,x=10*k-k*p);let y=n-.08*(c-p),z=randomBoolean();a.stroke(e);a.fill(g);drawFogliaBez(a,d,l,v,x,y,m,r,q,!1,z,!1,.5,.5,f);drawFogliaBez(a,
d,l,v,x,y,m,r,q,!1,z,!1,.5,.5,0)}return l}
function drawMandalaCenter(a,d,b,c,e,g,f){randomHash(.6*b,.8*b);a.stroke(g);a.noFill();a.strokeWeight(f);c=int(randomHash(4,8));for(b/=c;0<c;c--){f=b*c;let k=randomHash(.2*f,.9*f),l=int(randomHash(5,12)),n=randomHash(.1,.7),m=randomHash(.1,.9),q=randomHash(0,.3),r=randomHash(.1,.3),u=randomBoolean(),p=randomBoolean(),v=randomBoolean(),x=randomHash(.1,.9),y=randomHash(.1,.8);a.stroke(e);a.fill(g);drawFogliaBez(a,d,l,f,k,n,m,q,r,u,p,v,x,y,30);drawFogliaBez(a,d,l,f,k,n,m,q,r,u,p,v,x,y,20);a.stroke(g);
a.fill(e);drawFogliaBez(a,d,l,f,k,n,m,q,r,u,p,v,x,y,10);drawFogliaBez(a,d,l,f,k,n,m,q,r,u,p,v,x,y,0)}}function drawManyCircle(a,d,b,c,e,g,f,k){let l=TWO_PI/b;for(let n=0;n<f;n++)for(let m=0;m<b;m++){let q=d.x+sin(m*l+k)*c,r=d.y+cos(m*l+k)*c;a.circle(q,r,e-g*n)}}function makeStruct(a){a=a.split(" ");var d=a.length;return function(){for(var b=0;b<d;b++)this[a[b]]=arguments[b]}}let VarCoord=makeStruct("x y"),VarCircle=makeStruct("x y r");
function calcDistPunti(a,d,b,c){return sqrt(pow(b-a,2)+pow(c-d,2))}function calcDistPuntiCoord(a,d){return abs(sqrt(pow(d.x-a.x,2)+pow(d.y-a.y,2)))}function findPoints(a,d,b,c){v1=createVector(a.x,a.y);v2=createVector(d.x,d.y);v3=p5.Vector.sub(v1,v2);angle_h=v3.heading();LX=b*cos(angle_h+c);LY=b*sin(angle_h+c);RX=b*cos(angle_h-c);RY=b*sin(angle_h-c);a=[];a[0]=new VarCoord(v1.x+LX+cos(angle_h),v1.y+LY+sin(angle_h));a[1]=new VarCoord(v2.x+LX+cos(angle_h),v2.y+LY+sin(angle_h));return a}
function calcolaAngolo(a,d){return atan2(d.y-a.y,d.x-a.x)}function findPointsRetta(a,d,b){v1=createVector(a.x,a.y);LX=d*cos(b);LY=d*sin(b);return new VarCoord(v1.x+LX+cos(b),v1.y+LY+sin(b))}function calcPuntoRettaCoord(a,d,b){angle=calcolaAngolo(a,d);return findPointsRetta(a,b,angle)}
function calcPuntoRetta(a,d,b,c,e,g){let f,k=1;a=Math.trunc(a);d=Math.trunc(d);b=Math.trunc(b);c=Math.trunc(c);b<=a&&c<=d&&(k=-1);d==c?(g.x=a+e*k,g.y=d):a!=b?(f=(d-c)/(a-b),b=(b*d-a*c)/(b-a),0>f&&d<c&&(k=-1),g.x=(a*sqrt(1+pow(f,2))+e*k)/sqrt(1+pow(f,2)),g.y=f*g.x+b):(g.x=a,g.y=d+e*k)}
function pointInside(a,d,b){for(var c=!1,e=0,g=0;g<b.length;g++)e<b.length-1?e++:e=0,f_valuta=(b[e].x-b[g].x)*(d-b[g].y)/(b[e].y-b[g].y)+b[g].x,(b[g].y>=d&&b[e].y<d||b[g].y<d&&b[e].y>=d)&&a<f_valuta&&(c=!c);return c}function distAngolare(a,d){a=Math.abs(a-d);a>PI&&(a=TWO_PI-a);return a}function insideRange(a,d,b){return a<d?d:a>b?b:a}
function intersect_point(a,d,b,c){b=((c.x-b.x)*(a.y-b.y)-(c.y-b.y)*(a.x-b.x))/((c.y-b.y)*(d.x-a.x)-(c.x-b.x)*(d.y-a.y));return new VarCoord(a.x+b*(d.x-a.x),a.y+b*(d.y-a.y))}function calcCoordMatrix(a,d,b,c,e,g){var f=calcDistPuntiCoord(a,d);f=calcPuntoRettaCoord(a,d,f*e);var k=calcDistPuntiCoord(c,b);e=calcPuntoRettaCoord(c,b,k*e);k=calcDistPuntiCoord(d,b);d=calcPuntoRettaCoord(d,b,k*g);b=calcDistPuntiCoord(a,c);a=calcPuntoRettaCoord(a,c,b*g);return intersect_point(f,e,d,a)}
function findCircleIntersect(a,d,b){for(let c=0;c<a.length;c++)if(calcDistPunti(a[c].x,a[c].y,d,b)<a[c].r)return!0;return!1}
function calcPuntParalleli(a,d,b,c,e){let g,f,k,l=[];a=Math.trunc(a);d=Math.trunc(d);b=Math.trunc(b);c=Math.trunc(c);l[0]=new VarCoord(0,0);l[1]=new VarCoord(0,0);l[2]=new VarCoord(0,0);l[3]=new VarCoord(0,0);f=a;k=1;a>b&&(k=-k);if(a!=b){var n=(d-c)/(a-b);g=(b*d-a*c)/(b-a);f=(f*sqrt(1+pow(n,2))-k*e)/sqrt(1+pow(n,2));var m=-1/n;n=n*f+g-m*f;l[0].x=(f*sqrt(1+pow(m,2))-e)/sqrt(1+pow(m,2));l[0].y=m*l[0].x+n;l[1].x=(f*sqrt(1+pow(m,2))+e)/sqrt(1+pow(m,2));l[1].y=m*l[1].x+n}f=a;m=d;if(d==c||1>abs(d-c))l[0].x=
f-k*e,l[0].y=m+e,l[1].x=f-k*e,l[1].y=m-e;a==b&&(d>c&&(k=-k),l[0].x=f+e,l[0].y=m-k*e,l[1].x=f-e,l[1].y=m-k*e);f=b;k=-1;a>b&&(k=-k);a!=b&&(n=(d-c)/(a-b),g=(b*d-a*c)/(b-a),f=(f*sqrt(1+pow(n,2))-k*e)/sqrt(1+pow(n,2)),m=-1/n,n=n*f+g-m*f,l[3].x=(f*sqrt(1+pow(m,2))-e)/sqrt(1+pow(m,2)),l[3].y=m*l[3].x+n,l[2].x=(f*sqrt(1+pow(m,2))+e)/sqrt(1+pow(m,2)),l[2].y=m*l[2].x+n);f=b;m=c;if(d==c||1>abs(d-c))l[3].x=f-k*e,l[3].y=m+e,l[2].x=f-k*e,l[2].y=m-e;a==b&&(l[3].x=f+e,l[3].y=m-k*e,l[2].x=f-e,l[2].y=m-k*e);return l}
function drawMainTest_001(a,d){if(9==d){a.background(255);3>randomHash(0,10)&&(p_num_colonne=p_num_righe=2);d=!1;3>randomHash(0,10)&&(bordino=5);3>randomHash(0,10)&&(d=!0);var b=p_sfondo.sort(()=>.5-Math.random());let k=[],l=[],n=[];var c=[];let m=(w-2*dimBordo)/p_num_colonne,q=(h-2*dimBordo)/p_num_righe;randomHash(0,1E3);var e=0;for(var g=0;g<p_num_colonne;g++){k[g]=[];l[g]=[];n[g]=[];c[g]=[];for(var f=0;f<p_num_righe;f++)a.noStroke(),a.fill(b[e]),a.rect(dimBordo+g*m+bordino,dimBordo+f*q+bordino,
m-2*bordino,q-2*bordino),c[g][f]=p_sfondo[e],k[g][f]=randomHashArray(p_col_layer1),l[g][f]=randomHashArray(p_col_layer1),n[g][f]=randomHashArray(p_col_black),e++}b=randomHash(0,1E4);c=createGraphics(m-2*bordino,q-2*bordino);if(d){e=new VarCoord(0,0);g=new VarCoord(0,q-2*bordino);f=new VarCoord(m-2*bordino,q-2*bordino);let r=new VarCoord(m-2*bordino,0);drawTexture([e,g,f,r],11,[18,0,"#E1C699",1,[220,220,220],5,[30,30,30,120],15],c)}for(e=0;e<p_num_colonne;e++)for(g=0;g<p_num_righe;g++)d&&a.image(c,
dimBordo+e*m+bordino,dimBordo+g*q+bordino),f=new VarCoord(dimBordo+e*m+m/2,dimBordo+g*q+q/2),drawCompleteMandala(a,f,m,[n[e][g],255,k[e][g],l[e][g]],int(.012*m),b)}};
